config/routes.rb
Rails.application.routes.draw do

 resources :cocktails, only: [:index, :show, :new, :create] do
  resources :doses, only: [:new, :create]
end

resources :doses, only: [:destroy]
end



# Rails.application.routes.draw do
#   resources :restaurants do
#     resources :reviews, only: [ :index, :new, :create ]
#   end
#   # resources :reviews, only: [ :show, :edit, :update, :destroy ]
# root to: 'restaurants#index'
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Coctail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/new"
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
  end

  def create
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/destroy.html.erb
<h1>Cocktails#destroy</h1>
<p>Find me in app/views/cocktails/destroy.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>
<%= render 'form' %>

app/views/cocktails/index.html.erb
<h1>Cocktails#index</h1>
<p>Find me in app/views/cocktails/index.html.erb</p>

app/views/cocktails/new.html.erb
<h1>Cocktails#new</h1>
<p>Find me in app/views/cocktails/new.html.erb</p>
<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>